name: Lilypond Generator
description: Run make in a context where lilypond is available
author: '@holgerpeters'

inputs:
  path:
    description: path in which make is to be executed
    required: true
    default: .

runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.path }}

branding:
  icon: underline
  color: blue
