name: 'Lilypond Generator'
description: 'Run Lilypond tool with the given set of arguments to generate music sheets'
author: '@alexandre-touret'

inputs:
  args:
    description: 'Arguments for Lilyponid'
    required: true
    default: '-h'

runs:
    using: 'docker'
    image: 'docker://docker.pkg.github.com/alexandre-touret/lilypond-github-action/lilypond'
    args:
      - ${{ inputs.args }}

branding:
  icon: 'underline'
  color: 'blue'
